### ISSUE TITLE
cannot download files: no such file or directory

### ISSUE THREAD

**Issue by LoreVE** [marbl/Krona#113]
I cannot download the nucl_est.accession2taxid.gz and nucl_gss.accession2taxid.gz files (all other files can be downloaded). I get an error message both when I want to download them manually ("no such file or directory"/"this site can't be reached") or when I run updateAccessions.sh both locally and on an HPC server ("Update failed. Is your internet connection okay?" after trying to fetch nucl_est.accession2taxid.gz). I tried a few times since yesterday and I also tried different browsers/different PCs. It is also not a memory/storage issue...

**Comment by LoreVE** [comment]
I guess it has something to do with the warning you see on the NCBI nucleotide website: "The Nucleotide database will include EST and GSS sequences in early 2019. Read more."

**Comment by gerners** [comment]
I have the same problem, the files available at NCBI have changed their name (and content I assume), now only these two files are available:
ftp://ftp.ncbi.nih.gov/pub/taxonomy//accession2taxid/nucl_gb.accession2taxid.gz
ftp://ftp.ncbi.nih.gov/pub/taxonomy//accession2taxid/nucl_wgs.accession2taxid.gz

but no 'nucl_est' anymore, throwing the error as described by LoreVE.

Could you update that part of the updateAccession.sh?

Thanks!

**Comment by ondovb** [comment]
Thanks for the info! Should now be fixed in [v2.7.1](https://github.com/marbl/Krona/releases/tag/v2.7.1).

**Comment by LoreVE** [comment]
Thanks for the quick update!
