### ISSUE TITLE
Where is the archive?

### ISSUE THREAD

**Issue by iquasere** [marbl/Krona#140]
In [install instructions](https://github.com/marbl/Krona/wiki/Installing), it says ```To install KronaTools, unpack the archive```. What archive is this talking about? Can we just download the github project and install from there?

**Comment by iquasere** [comment]
If I download the github project, running install.pl doesn't create the symlinks correctly, and I can't access the tools. Where are they stored?

**Comment by albaguillen13** [comment]
Hi there!

I have the same doubt. I can't fin the "archive" and I don't know how to achieve it.

**Comment by ReneKat** [comment]
Hello @iquasere 
Navigate over to the Code. You will see a green button saying Clone or Download. Click on the Download Zip. Download the archive (zipped file) into a common location for your programs. After you unpack the archive, the directory is called Krona-master. Inside Krona-master there is another directory KronaTools. This is the directory you need to be in before running `./install.pl`
Hope that helps!

**Comment by iquasere** [comment]
Thank you, it did clarify everything I needed to know! And congratulations on a great tool!
