### ISSUE TITLE
download page empty

### ISSUE THREAD

**Issue by miraSantos** [marbl/Krona#149]
Hi I'd like to download krona tools but the downloads page is empty. Where can I find the download?

**Comment by skoren** [comment]
I assume you mean the download link on the wiki page? The link was incorrect, it's fixed now. You can also go to the releases page to download.

**Comment by miraSantos** [comment]
?Yes! Thank you so much!


Best Regards,
Miraflor Santos

PhD Student, Biological Oceanography
MIT-WHOI Joint Program
email: miras@mit.edu
cell: 858.436.4453

________________________________
