### ISSUE TITLE
Trademark restrictions permit distribution by Debian

### ISSUE THREAD

**Issue by tillea** [marbl/Krona#15]
Hello,

I'm a member of the Debian Med team which is a subgroup of Debian to package free software in life sciences and medicine for official Debian.  I created a Debian package of Krona since it is used in another package we intend to provide.

Unfortunately the Debian ftpmaster has  [rejected](https://lists.alioth.debian.org/pipermail/debian-med-packaging/2016-August/044989.html) the package due to the trademark restrictions.  I wonder whether you might consider relaxing this restriction to enable me a simple solution for packaging.  Since I only needed to adapt the install.pl script I could avoid the patch by rewriting the install procedure but this might mean extra work for no real profit.

BTW, if you checkout the [patch](https://anonscm.debian.org/git/debian-med/kronatools.git/tree/debian/patches/fix_install_script.patch) I also fixed a spelling mistake (second chunk of the patch) you might like to take over.

If you might want to stick to the trademark restrictions I could also provide a patch for the install script which takes an optional argument to override $scriptPath.  Please let me know what you might prefer.

Kind regards

         Andreas.

**Comment by tillea** [comment]
Well, after having written the last paragraph inspired me to solve the install script issue.  Feel free to provide [this slightly enhanced install.pl script](https://anonscm.debian.org/git/debian-med/kronatools.git/tree/debian/install.pl) in your next version.

However, I think the issue with the trademark restriction remains since we are not allowed to fix possible bugs in the scripts in case a Debian user might report an issue.

Kind regards

         Andreas.

**Comment by ondovb** [comment]
Hi Andreas,
Is the issue mainly that you need to call `install.pl` from somewhere other than the source directory? If so, I would prefer to fix that directly rather than add another argument.

For the spelling error, the script name should actually be capitalized, so I will fix that in the repo (I'm working on OS X, which ignores case).

**Comment by tillea** [comment]
Hi,

thanks for your quick reply.

On Thu, Aug 04, 2016 at 10:17:35AM -0700, ondovb wrote:
> Hi Andreas,
> Is the issue mainly that you need to call `install.pl` from somewhere other than the source directory? If so, I would prefer to fix that directly rather than add another argument.

Its not "calling from" but rather "installing to".  I think its quite
usual for installers taking arguments where to install the files.  Under
Debian the executables are installed to /usr/bin calling scripts under
/usr/share/perl5/<packagename>.  I'm calling the script with the
additional parameter as:

  debian/install.pl -prefix debian/$(DEBPKGNAME)/usr -taxonomy /var/lib/$(DEBPKGNAME)/taxonomy -scriptpath "../share/perl5/KronaTools/scripts"

> For the spelling error, the script name should actually be capitalized, so I will fix that in the repo (I'm working on OS X, which ignores case).

OK, fine with me - even if capitalisation in general feels unusual under
UNIX systems.

However, the main point of the trademark restrictions remains:  In case
a user might provide a fix we are not allowed to apply this as a patch
quickly which is not an ideal situation.

Kind regards

      Andreas.

-- 
http://fam-tille.de

**Comment by ondovb** [comment]
I see. The KronaTools architecture is currently dependent on the scripts remaining in the package directory to find libraries and other data, so this patch wouldn't be enough. If you need everything in system directories it may be easier to put the whole package in var/lib/ or share/ than trying to restructure it.

The trademark restrictions come from DHS, our funding source, and would be difficult to change, but we do try to address issues promptly when they come up.

**Comment by tillea** [comment]
On Fri, Aug 05, 2016 at 06:19:45AM -0700, ondovb wrote:
> I see. The KronaTools architecture is currently dependent on the scripts remaining in the package directory to find libraries and other data, so this patch wouldn't be enough. If you need everything in system directories it may be easier to put the whole package in var/lib/ or share/ than trying to restructure it.
> 
> The trademark restrictions come from DHS, our funding source, and would be difficult to change, but we do try to address issues promptly when they come up.

This would be helpful, thanks.

     Andreas.

-- 
http://fam-tille.de
