### ISSUE TITLE
Incorrect version info

### ISSUE THREAD

**Issue by kim-fehl** [marbl/Krona#166]
It seems that version info has not been updated in the latest release -- all scripts still output version 2.7.1 and not 2.8 when run without parameters. It would be also helpful to have some standard `--version` parameter, as now I have to write this in my installation test scripts:
`ktImportTaxonomy | head -2 | tail -1 | cut -d" " -f2-3`

**Comment by ondovb** [comment]
Fixed in [2.8.1](https://github.com/marbl/Krona/releases/tag/v2.8.1).
