### ISSUE TITLE
Exporting raw data from krona plot

### ISSUE THREAD

**Issue by azam17** [marbl/Krona#173]
I ran a prediction analysis using the PGPT-Pred service at https://plabase.informatik.uni-tuebingen.de/ and they provided me a link to krona plot. I was wondering could i export the raw data from the krona plot itself in an excel/csv format.

**Comment by spatz0142** [comment]
**Sorry for late reply, but we saw your issue reported here today.** 
**The hierarchical data shown in the Krona plot, either for blastp or the strict blastp+hmmer results, is now available for download as tsv format (tab separated) on the result page.**

Please, for any issues related to PLaBAse please contact us directly or additionally via plabase@inf.uni-tuebingen.de as mentioned by email. That way we are able to reply or implement your suggestion asap.

Thanks!
