### ISSUE TITLE
Taxonomy location variable

### ISSUE THREAD

**Issue by donutbrew** [marbl/Krona#18]
Would it be possible to add a check for an environment variable, say $KT_TAXONOMY, and use that to set the location of the taxonomy files? Perhaps a command line option instead or in addition? There are cases where in a shared environment, it is better to have your own taxonomy files and it is difficult/undesirable to update the taxonomy for all users/all cases.

**Comment by ondovb** [comment]
If I'm understanding correctly, this should already be available in the latest version (via command line options). You can provide a directory when updating like:

    updateTaxonomy.sh /custom/dir

And then point import scripts to it like:

    ktImportBLAST -tax /custom/dir ...

**Comment by donutbrew** [comment]
Yikes. I have been using this for years and I have never notices that option. Yes, that is exactly what I'm looking for :+1:
