### ISSUE TITLE
now, on windows, I can not open the HTML file, Why?

### ISSUE THREAD

**Issue by yabingHai** [marbl/Krona#20]

**Comment by ondovb** [comment]
Charts are working for me in Windows 10 with Edge. Did something on your system change, like browser or KronaTools version? When you can't open it, is there any kind of error message?

**Comment by ondovb** [comment]
If you are using the Excel Template, the latest release, [2.4](https://github.com/marbl/Krona/releases/tag/xl2.4), should solve this problem.
