### ISSUE TITLE
New to Krona, Having Trouble Generating Chart from previous OTU table

### ISSUE THREAD

**Issue by rsmote** [marbl/Krona#24]
Hello, I am not much of a computer person, so I cannot figure out what I'm doing wrong.  I have an OTU table consisting of the number of OTUs and the phylogeny.  When I import the file (which I have attached an example here; columns are [# of OTUs, Kingdom, Phylum, Class, Order, Family, Genus, Species]) using Krona tools, an issue arises and the chart just says 100% unclassified (picture attached). I'm sure it's most likely my input file, but I have no idea how to approach the issue. Thank you for any help you may provide!

![screen shot 2016-11-09 at 15 43 34](https://cloud.githubusercontent.com/assets/23366679/20154061/b304a1f2-a693-11e6-93ca-e2f7b0e72c3a.png)

[test1kronastudy1.txt](https://github.com/marbl/Krona/files/581796/test1kronastudy1.txt)

**Comment by ondovb** [comment]
It looks like the line endings for this file are Classic Mac format; they will have to be Unix format for KronaTools. You can change this with TextWrangler.

**Comment by rsmote** [comment]
Ah yes, this fixed the issue. You're a saint! I great appreciate it!
