### ISSUE TITLE
Option to output svg directly rather than interactive html

### ISSUE THREAD

**Issue by JohnLonginotto** [marbl/Krona#25]
This would be a nice feature for those who wish to use Krona's output in automated systems :)

**Comment by ondovb** [comment]
Agreed. There is a workaround in the discussion of #5, which I have reopened as an enhancement.

**Comment by JohnLonginotto** [comment]
Ah, i see - in the interests of transparency I was asking on behalf of stevekm (we are both users of the same forum) who restarted discussion #5. I hadn't realised he had also asked. Just stating this so you are aware that interest in this feature isn't 2x what it might otherwise appear to be. All the best!
