### ISSUE TITLE
KtImportBLAST and some accession numbers.

### ISSUE THREAD

**Issue by WardDeb** [marbl/Krona#28]
Hello,

We are using Kronatools to visualise a large number of blasted sequences. 
Recently when using the ktImportBLAST module, we receive a warning that says that some accessions are not in a valid format and thus ignored. These are some examples of the accessions that generate this warning:
2AYV_A P0C9A6.1 Q53RJ5.1 3SQ2_A 2X9I_A 2X5G_A 3NE6_A A4WGV2.1 2XEE_A 2UYH_A P0C9B9.1 2OXQ_A 3HXL_A

The weird thing is that these are genuine protein accessions. 

Is there a way to make sure that this kind of acession numbers are not ignored?

Thanks in advance.

**Comment by ondovb** [comment]
It looks like the format should be relaxed in the next version to accommodate some of these less standard accessions. This can be accomplished temporarily by commenting out lines 969-973 of KronaTools/lib/KronaTools.pm:

    #	if ( $acc !~ /^\d+$/ && $acc !~ /^[A-Z\d]+_?[A-Z\d]+(\.\d+)?$/ )
    #	{
    #		$invalidAccs{$acc} = 1;
    #		return undef;
    #	}

Note, however, that the ones that begin with a number are not currently in the accession-taxid lookup table provided by NCBI and so cannot be used anyway.

**Comment by WardDeb** [comment]
Thanks for the quick response, this seems to work.
