### ISSUE TITLE
<color ...  /> with empty xml element doesn't render

### ISSUE THREAD

**Issue by DWgit** [marbl/Krona#34]
Hello,

This is a minor item that could be fixed in the doc or code.

I'm using python xml.etree.ElementTree to generate Krona xml. ET detected that <color ...></color> has an empty element and appropriately generated <color ... />. That empty element prevents Krona from rendering.

To see the issue, edit the [Example Krona Chart](http://krona.sourceforge.net/examples/xml.krona.html) and replace the existing <color ...></color. with:

```<color attribute="grams" valueStart="0" valueEnd="55" hueStart="120" hueEnd="240"/>```

Thanks very much.

**Comment by ondovb** [comment]
The XML chart data exist within XHTML, which only allows specific tags to be self-closing (e.g. `<img../>`). For the data to be properly loaded into the DOM, so you will have to find a way to either prevent ET from collapsing these or put them back as paired tags with post-processing.

**Comment by DWgit** [comment]
Yes, ET supports write(..., short_empty_elements=False).  Thanks for the quick feedback.

**Comment by ondovb** [comment]
Great, let us know if you run into any other snags.
