### ISSUE TITLE
Too many query IDs to store in chart?

### ISSUE THREAD

**Issue by LucasvdGouw** [marbl/Krona#37]
When running krona with ktImportNLAST, I get the following warning: Too many query IDs to store in chart; storing supplemental files in 'blast.krona.html.files'. How can I resolve this issue?

**Comment by ondovb** [comment]
No need to resolve it; it's just to let you know that extra files are being produced besides the main output. The chart will still work without these files present, just without the functionality to list query IDs per wedge.

**Comment by r0sies** [comment]
Hi, when we run krona on a large sample set, it produces 1.9 million files in the krona.html.files This exceeds our iNode limit (number of files) on a shared HPC cluster. Is there a way to not generate that folder? Thanks
