### ISSUE TITLE
Unrecognized escape \A passed through at KronaTools.pm line 1703.

### ISSUE THREAD

**Issue by chienchi** [marbl/Krona#39]
Hi,  

I ran into an warning message as title and looking at code source.  It looks like there is a spurious backslash @ line 1703 of version 2.6 ( line 1921 of version 2.7).     

     $summaryText = " ${memberTag}\All=\"members\"";

Regards,
Chienchi

**Comment by ondovb** [comment]
Thanks, the backslash is indeed unnecessary and will be removed in the next version. However, in this context it should be ignored by Perl and so might not be the source of the warning you saw. I could take a look at your chart if you'd like.
