### ISSUE TITLE
UTF-8 encoding

### ISSUE THREAD

**Issue by coolbanans** [marbl/Krona#40]
I'm trying to load the results from Krona as part of my Shiny (R) app. Shiny requires utf-8 encoding. The charset in the HTML from Krona is defined as utf-8, but it wont load into Shiny. If i save the HTML with utf-8 encoding from a text editor, it works fine. Is there a way to ensure encoding when using the excel template?

**Comment by ondovb** [comment]
This seems to come from the '...' button when the legend is hidden, but also wedge names with characters outside of basic Latin, e.g. accented letters. I'll have to fix this in the next version of the template. Until then your workaround should be okay as long as you don't need full Unicode in your names. Another option would be `ktImportText` in KronaTools, which should produce well-formed UTF-8.

**Comment by coolbanans** [comment]
Ok, thanks. I'll keep an eye on future versions. Cheers

**Comment by ondovb** [comment]
The version available [here](https://github.com/marbl/Krona/raw/master/ExcelTemplate/Krona.xltm) should fix this. I had to switch from UTF-8 to UTF-16, but I don't think that should be of any consequence. Note that the format for multiple samples has also changed, but now allows more than two. This version will become the next official release barring any other issues.

**Comment by ondovb** [comment]
If you explicitly need UTF-8 (not sure if Shiny supports UTF-16, in retrospect), I could return to ASCII and remove Unicode characters from the Krona rendering code. You would also have to avoid any non-ASCII characters in the template fields.

**Comment by coolbanans** [comment]
Thanks, that would be preferable for my use case. Unfortunately Shiny doesn't seem to support UTF-16. Either way, it's not too challenging for me to save with utf-8 encoding elsewhere. Cheers

**Comment by ondovb** [comment]
Ok, the latest version in the repo ([same link](https://github.com/marbl/Krona/raw/master/ExcelTemplate/Krona.xltm)) should provide clean UTF-8, unless there is anything beyond ASCII in the input fields, in which case it will fall back on UTF-16.

**Comment by ondovb** [comment]
This has been released in [2.5](https://github.com/marbl/Krona/releases/tag/xl2.5); please re-open if it doesn't work for you.
