### ISSUE TITLE
NCBI is phasing out sequence GIs

### ISSUE THREAD

**Issue by odoublewen** [marbl/Krona#48]
Just curious -- Will NCBI's announcement (announced March last year) affect any Krona functionality?  I was under the impression that the taxanomic db that Krona builds (with updateTaxonomy.sh) is keyed off of gi numbers (not accession.version).

https://www.ncbi.nlm.nih.gov/news/03-02-2016-phase-out-of-GI-numbers/

**Comment by ondovb** [comment]
Hi @odoublewen,
You are correct, KronaTools did key on GIs until [version 2.7](https://github.com/marbl/Krona/releases/tag/v2.7), which switched to accessions in anticipation of this change. There should be no issues for users as long as you are using the latest version, save for #28 at the moment.

**Comment by odoublewen** [comment]
Thanks!  Sorry, I should have checked the release notes, you had this answer documented nicely there.  Thanks for the superb software and for all the improvements.
