### ISSUE TITLE
FTP is insecure and should be deprecated

### ISSUE THREAD

**Issue by datakid** [marbl/Krona#54]
Can the taxonomies be moved somewhere more contemporary?

As a hospital, and given current situation with security, our IT team has decided that ftp will be permanently blocked without exception. It's annoying, but they aren't wrong.

**Comment by ondovb** [comment]
These data are hosted by NCBI, which uses Aspera instead of sftp:
https://www.ncbi.nlm.nih.gov/books/NBK242625/

**Comment by datakid** [comment]
Thanks for the aspera link. That's the second rec I've had for Aspera.
