### ISSUE TITLE
Formatting for ImportText.pl ?

### ISSUE THREAD

**Issue by shu251** [marbl/Krona#55]
Perhaps I'm misunderstanding the directions posted in the wiki on this, but when I import text like the attached, I do not get the same type of output as the example (nutritional information). See attached the text file and the output html file. 
Any suggestions on how I'm improperly formatting?

Command:
perl ImportText.pl DNA_krona.txt

[DNA_krona.txt](https://github.com/marbl/Krona/files/1064607/DNA_krona.txt)

**Comment by darnassiano** [comment]
I suggest you to use the Excel Template Instead, your taxonomic category goes into the category columns

**Comment by ondovb** [comment]
I see two potential issues:
- The line endings in the file are Classic Mac (`\r`); KronaTools expects Unix (`\n`).
- The numbers in the first column seem to be just a sequence; these should be the quantity to contribute to the specified wedge. If each line should be the same quantity, they can all be 1 or you can omit the first column and pass `-q`.

**Comment by coyk** [comment]
Is there a taxonomic template out there??  Where did you get the information that the numbers in the first column specify contribution?  The granola excel template is inscrutable to me.

**Comment by ondovb** [comment]
The text format is specified [here](https://github.com/marbl/Krona/wiki/Importing-text-and-XML-data), and regarding the first column, specifically: "Each line should be an optional quantity (use -q if quantities are omitted) followed by list of wedges to contribute to".
