### ISSUE TITLE
Installing Excel template on Mac

### ISSUE THREAD

**Issue by echvet** [marbl/Krona#56]
I'm receiving an error message when trying to open the downloaded install_Mac file on the Excel Template. It says the file is damaged and can't be opened. Anyone finding similar or have any ideas?

**Comment by deepthoughts** [comment]
Try to download using another browser. I had this behavior with some other software. 
OR 
use this command from the terminal to download Krona
```
curl -LOk https://github.com/marbl/Krona/releases/download/v2.7/KronaTools-2.7.tar
```

```
tar xvf KronaTools-2.7.tar
```

```
cd KronaTools-2.7
```

**Comment by ondovb** [comment]
The template can be used without running the install scripts, and those scripts have in fact been removed in the latest release ([2.5](https://github.com/marbl/Krona/releases/tag/xl2.5)).
