### ISSUE TITLE
Cannot use Krona

### ISSUE THREAD

**Issue by itiago** [marbl/Krona#58]
Hi
I've installed excel 97 on my PC, and already run for several times the install_Windows VBScript, but it does not do any thing. I've also installed office 2016 in my PC, could this be interfering? (but I cannot work with out it...).
Can any one help me? I've tried to import/had data to the template Krona.excel to see if I could produce some thing but, I just cannot make it work, and I really wanted to produce Krona graphics from metagenomic data from several samples, all in the same file.
Thank you for any help.
kind regards
Igor

**Comment by ondovb** [comment]
Hi Igor,
The install script should make it show up in templates, but this is for convenience and not necessary to use it. You should be able to make charts directly from the Excel template in the download. When you say you can't make it work, is there an error message, or any kind of output?

**Comment by itiago** [comment]
Hi Brian
Thank you for your reply.
I have a table with several samples values and phylogenetic classification for each otu, I've tried to run the macro in the worksheet where the table is, but the error shows... a file html is generated but with nothing on it.
That is why I say "I can't make work...."
thanks for any help
Best
Igor

![image](https://user-images.githubusercontent.com/16780953/28239943-27a9f504-696f-11e7-9da8-19e76f86b94e.png)
![image](https://user-images.githubusercontent.com/16780953/28239950-59645300-696f-11e7-8646-98b056930103.png)

**Comment by mprarthana** [comment]
Hey, 

I have exactly the same issue. When I try to create a chart, a html file gets saved. However, when I try to open it, its a blank page. Kindly let me know how to fix this. Thanks in advance!

**Comment by ondovb** [comment]
The data need to be placed where the example data are on the main sheet. From your image it looks like they will also need to be reformatted to match the template.
