### ISSUE TITLE
Unassigned no hits?

### ISSUE THREAD

**Issue by toddknutson** [marbl/Krona#6]
I am providing Krona at file with two columns (a query id and an NCBI taxonomy ID). For example:
````
query1     543  
query2     1  
query3     0  
````
My call to Krona version 2.6 is: `ktImportTaxonomy -i -k -o krona.html` and my resulting pie charts would assign query1 to taxonID 543, query2 to "unassigned root" and query3 to "unassigned root" but give me a warning in the terminal that "0" is an unrecognized taxonomy ID and those queries were added to the "unassigned root" group. This produces two wedges.

Instead, I would like to see three wedges, one for 543, one for unassigned root, and one for "no hits" or "unclassified" or something like that. How can I do this? I don't want all my "0" taxonomy IDs to be added into the "unassigned root" group.

Thanks for any help!

**Comment by toddknutson** [comment]
I may have solved my own issue -- or at least I found a workaround. All of my queries assigned to "0" are truly unclassified, whereas my queries assigned to "1" are classified as "unassigned root." I looked up NCBI's taxonomy and there is a top level for "unclassified" which has a taxon ID number: 12908. Thus, if simply change all my "0"s to "12908", I get the Krona chart I'm looking for.

**Comment by ondovb** [comment]
It looks like this has actually been broken since 2.5. I just pushed 2.6.1 with a fix.

**Comment by toddknutson** [comment]
Great, thanks! Version 2.6.1 now works as I originally wanted: a "0" is called "no hits", and a "1" is called "unassigned root". If by chance you had a taxon ID of "12908" in your list, that would be called "unclassified sequences." Thanks again for the fix!
