### ISSUE TITLE
Error Message: "No variable-mapping2.txt file exists for project *insert name*"

### ISSUE THREAD

**Issue by osajid** [marbl/Krona#60]
Hello all,

I am using a Krona software from the bio-sequencing company: "Molecular Research DNA". Here is a link to  the krona program: http://www.mrdnafreesoftware.com/krona.html

I sent DNA samples to the company for sequencing, which later returned to me in the form of OTU.txt files for analysis, but I cannot do a simple run through of the program. At first I received this message:  "A Krona.xlsm file with the original Krona Excel template must be in the (same) directory (as the krona.exe file)". So, I came here to this github to use the Krona Excel Template. In order to use it, I had to remove 2 hidden worksheets from the macro enabled workbook for the program to run (I am not sure whether or not this is causing a problem in the program, but the Krona Excel Template still works fine). Once it did, I am now receiving this message: "No variable-mapping2.txt file exists for project *insert name*". Does anyone know what this means?

EDIT***: I have found the mapping file, but the error is still appearing.

(Note: I have tried simply copy and pasting my OTU.txt data into the excel template for instant use, but the HTML link does not show any data)

**Comment by ondovb** [comment]
This sounds like an issue with wrapper code from this analysis company, so they would probably have more insight. I can tell you, though, that the Krona Excel template will not work with its hidden worksheets deleted!
