### ISSUE TITLE
Krona-2.7 :: installer 

### ISSUE THREAD

**Issue by EricDeveaud** [marbl/Krona#68]
Hello, 

after running Krona-2.7 installer with prefix  I was really surprised to see that it only symlnk scripts from source directory to $PREFIX/bin directory.

problem here is that I want to installit on a NFS shared directory on our cluster that DOES not have access to the source directory. 

thus all links point to non existing files when run on exec nodes.

can you please provide a REAL installer ;-(

**Comment by EricDeveaud** [comment]
Yes it's called install policy 
I MUST follow the guidelines.

our install framework is hosted on a build machine that have write access to the NFS shared directory of our cluster. 
source directory is only available on this specific machine.

Installer MUST install not symlink.

**Comment by ondovb** [comment]
Maybe give the build machine a wrapper that copies the source and then installs? KronaTools needs its source folder one way or another.

**Comment by EricDeveaud** [comment]
LOL

**Comment by EricDeveaud** [comment]
maybe you should check some other installer
