### ISSUE TITLE
Installation with prefix

### ISSUE THREAD

**Issue by magic-trip** [marbl/Krona#7]
Dear Krona authors,
I want to perform local installation of krona on a linux cluster.
so I perform : 
./install.pl --prefix /my/path/
But, the program ktImportText doesn't work in that configuration
./ktImportText table.txt
Writing text.krona.html...
Can't read file '/../src/krona-2.0.js' [Aucun fichier ou dossier de ce type]
Please fix it !

**Comment by ondovb** [comment]
It sounds like adding "/my/path/bin" to your $PATH should fix this.

**Comment by magic-trip** [comment]
Thanks, it fixed the problem.

**Comment by ondovb** [comment]
I'll add a more useful error message for this case in the next version.
