### ISSUE TITLE
updateTaxonomy.sh errors 

### ISSUE THREAD

**Issue by xvazquezc** [marbl/Krona#8]
Hi,
I have been trying to install KronaTools 2.6.1 in our cluster and I find some errors when running `updateTaxonomy.sh`.

So, KronaTools after extraction is at `/srv/scratch/z3382651/KronaTools-2.6.1`, I enter in the folder and install it with no error at all. I tried:
`./install.pl --prefix /srv/scratch/z3382651/KronaTools-2.6.1`
`./install.pl --prefix /srv/scratch/z3382651/KronaTools-2.6.1 --taxonomy /srv/scratch/z3382651/KronaTools-2.6.1/taxonomy/`

So far, so good. But when running `updateTaxonomy.sh`, I get the following error:

> /updateTaxonomy.sh: line 115: cd: /srv/scratch/z3382651/metannotate/included_software/KronaTools-2.5/lib/../taxonomy: No such file or directory
> 
> \>>>>> Update failed.
>       Could not enter '/srv/scratch/z3382651/metannotate/included_software/KronaTools-2.5/lib/../taxonomy'. Did you run install.pl?

I could make the `updateTaxonomy.sh` by doing `./updateTaxonomy.sh taxonomy` but I get another error:
> ./updateTaxonomy.sh: line 99: ktGetLibPath: command not found

Afterwards starts updating though, but I'm not sure if it's going to be ok. I'm installing Krona as dependency of [GraftM](https://github.com/geronimp/graftM/wiki)

Any way to test the installation?

Thanks

**Comment by ondovb** [comment]
It looks like there is a conflict with the other version installed in Metannotate. You may be able to fix this by adding `/srv/scratch/z3382651/KronaTools-2.6.1/bin` to your `$PATH` (prepend for priority) and running `./updateTaxonomy.sh`. Note that if Metannotate shares this `$PATH`, it will also use the newer version, which may or may not cause problems.

**Comment by wwood** [comment]
Hi @xvazquezc - one thing to note here is that while GraftM requires Krona as a dependency, it does not require `updateTaxonomy.sh` to be run, because it does not use the taxonomy-related parts of Krona. In fact, it only uses `ktImportText`.

**Comment by sridhar0605** [comment]
I have the same issue, 

could you please help for further resolution please find below logs 

-bash-4.1$ ./install.pl --prefix /scratch/abcd/kraken/kraken_full/jj/KronaTools-2.6.1.
Creating links...

Installation complete.

To use scripts that rely on NCBI taxonomy, run updateTaxonomy.sh to build the
local taxonomy database.
-bash-4.1$ ls
data                install.pl   README.txt  taxonomy
deployResources.sh  lib          scripts     updateTaxonomy.sh
img                 LICENSE.txt  src
-bash-4.1$ ./install.pl --prefix /scratch/abcd/kraken/kraken_full/jj/KronaTools-2.6.1
Creating links...

Installation complete.

To use scripts that rely on NCBI taxonomy, run updateTaxonomy.sh to build the
local taxonomy database.
-bash-4.1$ ls
bin   deployResources.sh  install.pl  LICENSE.txt  scripts  taxonomy
data  img                 lib         README.txt   src      updateTaxonomy.sh
-bash-4.1$ ./install.pl --prefix /scratch/abcd/kraken/kraken_full/jj/KronaTools-2.6.1 --taxonomy /scratch/abcd/kraken/kraken_full/jj/KronaTools-2.6.1/taxonomy/
Creating links...
Linking taxonomy to /scratch/abcd/kraken/kraken_full/jj/KronaTools-2.6.1/taxonomy...

Installation complete.

To use scripts that rely on NCBI taxonomy, run updateTaxonomy.sh to build the
local taxonomy database.
-bash-4.1$ ls
bin   deployResources.sh  install.pl  LICENSE.txt  scripts  taxonomy
data  img                 lib         README.txt   src      updateTaxonomy.sh
-bash-4.1$ ./updateTaxonomy.sh
./updateTaxonomy.sh: line 99: ktGetLibPath: command not found
./updateTaxonomy.sh: line 115: cd: /../taxonomy: No such file or directory

>>>>> Update failed.
      Could not enter '/../taxonomy'. Did you run install.pl?

-bash-4.1$ ./updateTaxonomy.sh taxonomy
./updateTaxonomy.sh: line 99: ktGetLibPath: command not found

Creating taxonomy...

mkdir: cannot create directory `taxonomy': File exists
./updateTaxonomy.sh: line 115: cd: taxonomy: Too many levels of symbolic links

>>>>> Update failed.
      Could not enter '/../taxonomy'. Did you run install.pl?

-bash-4.1$ export PATH=$PATH:/scratch/abcd/kraken/kraken_full/jj/KronaTools-2.6.1/bin/
-bash-4.1$ ./updateTaxonomy.sh
./updateTaxonomy.sh: line 99: ktGetLibPath: command not found
./updateTaxonomy.sh: line 115: cd: /../taxonomy: No such file or directory

>>>>> Update failed.
      Could not enter '/../taxonomy'. Did you run install.pl?

-bash-4.1$ ./updateTaxonomy.sh taxonomy
./updateTaxonomy.sh: line 99: ktGetLibPath: command not found

Creating taxonomy...

mkdir: cannot create directory `taxonomy': File exists
./updateTaxonomy.sh: line 115: cd: taxonomy: Too many levels of symbolic links

>>>>> Update failed.
      Could not enter '/../taxonomy'. Did you run install.pl?

-bash-4.1$

**Comment by ondovb** [comment]
These errors should be fixed in the latest release, [2.7](https://github.com/marbl/Krona/releases/tag/2.7).

**Comment by ondovb** [comment]
Assuming all these issues were resolved by the overhauled updating scripts in the current version. Feel free to re-open or submit a new issue if anything still comes up.
