### ISSUE TITLE
Snapshot Functionality does not work anymore

### ISSUE THREAD

**Issue by your-highness** [marbl/Krona#83]
Dear Krona Devs,

Your library is very useful for visualisation of metagenomic data!

Currently, I am preparing a presentation with KronaCharts and would like to export the charts as SVG files. While this worked before (Feb 2018) with Chromium Version 66.0.3336.0 (32-Bit) on my Windows 10 and with Firefox 59.0.1 (64-Bit) on an Ubuntu 16.04 VM, neither Chromium nor Firefox display the SVG graphics. Both browsers only open a new empty tab.

When using Firefox 58.0.1 (64-Bit) on another Windows 7 Professional machine, the SVGs are displayed and can be saved. The generated svg can be opened in Chromium Version 66.0.3336.0 (32-Bit) on my Windows 10 and with Firefox 59.0.1 (64-Bit) on an Ubuntu 16.04 VM.

Do you have any idea what might cause this problem?

Best,
Johannes

**Comment by MLABuky** [comment]
I'm using Windows10 and 59.0.2 (64-bit) and having the same problem, no new tab but the screen blinks for a second and nothing happens

**Comment by your-highness** [comment]
I narrowed it down to updates in Firefox and Chromium. In the meantime, I am using a Firefox 58.0.1 installation to do snapshots.

**Comment by lp-brown** [comment]
Temporary workaround is as follows:

1. Enter Firefox configuration by typing "about:config" in address bar and accepting the risk statement.
2. Change the value of "security.data_uri.block_toplevel_data_uri_navigations" to **false**.

Top frame navigation to data URLs was blocked in Firefox v58 as a security feature.

**Comment by tolot27** [comment]
Isn't this a duplicate of #85, is it?

**Comment by lp-brown** [comment]
Ah yes @tolot27, you're right. Sorry, didn't see #85 !

**Comment by your-highness** [comment]
Seems to work now!

**Comment by AdeBC** [comment]
> Temporary workaround is as follows:
> 
> 
> 
> 1. Enter Firefox configuration by typing "about:config" in address bar and accepting the risk statement.
> 
> 2. Change the value of "security.data_uri.block_toplevel_data_uri_navigations" to **false**.
> 
> 
> 
> Top frame navigation to data URLs was blocked in Firefox v58 as a security feature.

This is exactly what I need. Thanks！

**Comment by ProcessY** [comment]
> Temporary workaround is as follows:
> 
> 1. Enter Firefox configuration by typing "about:config" in address bar and accepting the risk statement.
> 2. Change the value of "security.data_uri.block_toplevel_data_uri_navigations" to **false**.
> 
> Top frame navigation to data URLs was blocked in Firefox v58 as a security feature.

Lots of thanks! That really helps!
