### ISSUE TITLE
Snapshot Function is not working

### ISSUE THREAD

**Issue by Arjun9805** [marbl/Krona#85]
Hi all

The Snapshot function is not working. I have tried to export the chart in SVG format for my presentation but the it did not work. I have tried both in Firefox and Google-chrome and in both versions an empty window was popping-up.

Do you have any solution for this problem.

Thank you.

BR
Sri

**Comment by MLABuky** [comment]
I have this issue as well, Windows 10 and Firefox 59.0.2 (64-bit), I don't get a new window, the screen blinks for a second and nothing else happens

**Comment by andzandz11** [comment]
Snapshot fails completely for me even with Microsoft browsers or Chrome or Firefox.

**Comment by MLABuky** [comment]
I have had luck using the Firefox portable app for version 58.0.1
https://portableapps.com/apps/internet/firefox_portable

**Comment by andzandz11** [comment]
I can cofirm version 57 portable is working. It seems to be the case that 32-bit versions are okay, but 64-bit versions are not working. At least concerning Firefox

**Comment by emily-haggett** [comment]
also having this problem, Firefox and chrome 64-bit. Also tried on Firefox portable but had same issue

**Comment by andzandz11** [comment]
You have to edit your Firefox profile config file manually to disable automatic updates. Otherwise Firefox will instantly update itself without any way to stop it.

**Comment by gtsitsiridis** [comment]
Any news about this issue?

**Comment by gtsitsiridis** [comment]
I have tried the latest opera, chrome and firefox versions without any luck. It did work on firefox 58.0.1 though.

**Comment by tolot27** [comment]
The reason is described here: [Blocking Top-Level Navigations to data URLs for Firefox 59](https://blog.mozilla.org/security/2017/11/27/blocking-top-level-navigations-data-urls-firefox-59). It's the same with Chrome and Opera and SVGs were excluded meanwhile because they contain javascript.
