### ISSUE TITLE
How to import Krona chart as a chart instead of as a link to object, into the Powerpoint presentation slides?

### ISSUE THREAD

**Issue by LakshmyDurgasi** [marbl/Krona#90]
Hi 
Could someone please let me know how to import Krona charts into MS powerpoint.  I'd like to have Krona chart itself straight in the powerpoint slide instead of the hyperlink to the html/object as displayed in below slide
[Presentation1.pptx](https://github.com/marbl/Krona/files/2005985/Presentation1.pptx)

I have a 10 min presentation to give this Friday, so any help would be much appreciated.

**Comment by tolot27** [comment]
That's not possible, at least not without a plugin/addon which most likely won't work on a presentation system.
Just make a Screenshot or export as SVG and convert it to png.
If you really need an interactive Krona chart, you have to use a browser/link to the file.

**Comment by LakshmyDurgasi** [comment]
Thanks for the reply, much appreciate!
